### ISSUE TITLE
While compiling sasjs web, images are not being loaded from html

### ISSUE THREAD

**Issue by saadjutt01** [sasjs/cli#1046]
Need to process `img` tags in `index.html`.

Also for SAS9, path with three forward(`///`) slash should also be processed present in JS files.

Also add support for `jpg` in [sasjsout.ts](https://github.com/sasjs/cli/blob/main/src/commands/web/internal/sasjsout.ts)

**Comment by saadjutt01** [comment]
Ref: process `///` in JS files

> For SAS 9, you will just have to put all URLs in the index.html for now
> or embed them fully in the JS (no links)

**Comment by allanbowe** [comment]
Still a problem in the CLI:

<img width="680" alt="image" src="https://user-images.githubusercontent.com/4420615/154144320-583cb74d-d226-4c1c-95dc-29d7b4e0382b.png">
