### ISSUE TITLE
sasjs request on sas 9 does not error when the service is non-existent

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#1082]
When running against a service that does not exist:

![image](https://user-images.githubusercontent.com/4420615/147657552-dd5f4abf-175d-43c4-a4db-ec208515ecf9.png)

There is no error in the console.  The output json contains the message.  Which is fine, but the console should also print an error (and exit with a non-zero return code, ideally)

```
{
  "errorCode": 404,
  "errorMessage": "Stored process not found: /Public/app/frs/allan/something/random",
  "result": "",
  "name": "JobExecutionError"
}
```

**Comment by sabhas** [comment]
![Uploading Screenshot from 2023-02-15 18-32-50.png…]()
Could not reproduce this as this might have been fixed already in some other PR

**Comment by sabhas** [comment]
![Uploading Screenshot from 2023-02-15 18-32-50.png…]()
Could not reproduce this as this might have been fixed already in some other PR
