### ISSUE TITLE
Windows server tests issue on main branch

### ISSUE THREAD

**Issue by VladislavParhomchik** [sasjs/cli#1105]
![image](https://user-images.githubusercontent.com/83717836/151940097-d427ca46-6d03-4221-9d02-e85b54dfae52.png)

**Comment by YuryShkoda** [comment]
`flow.spec.server.ts`
![image](https://user-images.githubusercontent.com/25773492/151971466-5c429219-c906-42fd-b658-9ad68dc0c8e2.png)
