### ISSUE TITLE
Forbidden when creating contexts

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#111]
The following was returned from the CLI:

```
➜  /tmp sasjs context create -s SharedCompute.json -t globviya
An error has occurred when processing context. Forbidden. Check your permissions and user groups. 
traceId: f3020dddb774e035,path: /compute/contexts
:q!
```

the issue was that the CLIENT was generated without the correct scopes.  We should update the warning text to:

An error has occurred when processing context. Forbidden. Check your permissions and user groups, and also the scopes granted when registering your CLIENT_ID.

**Comment by YuryShkoda** [comment]
It's an adapter's issue.
https://github.com/sasjs/adapter/issues/114
