### ISSUE TITLE
Ability to manage folders from CLI in SAS 9

### ISSUE THREAD

**Issue by YuryShkoda** [sasjs/cli#117]
Related issue #73 

On SAS 9, the most reliable way to do this is using the [batch tools](https://discord.com/channels/@me/923930055418212372/960928912924369008).  This will necessitate the use of an SSH connection to SAS.

Additional variables will also be needed in the .env file:

* SSH_SERVER (to default to serverUrl)
* SSH_KEYFILE (to default to `~/.ssh/id_rsa`)
* SSH_USER (to default to `SAS_USERNAME`)
* META_SERVER (to default to serverUrl)
* META_PORT (to default to `8561`)
* SAS_TOOLS (to default to `/opt/sas/sas9/SASHome/SASPlatformObjectFramework/9.4/tools`)

The `SAS_USERNAME` & `SAS_PASSWORD` will have been captured from the `sasjs auth` command.

Running the `sasjs folder delete` command for a SAS9 target will result in the following:

1.  Extract `SAS_USERNAME` and de-coded `SAS_PASSWORD` from .env.target file
2.  Prepare script for SSH execution eg as follows:

```bash
#!/usr/bin/env bash
cd "$SAS_TOOLS"
./sas-delete-objects \\
  "$PATH_TO_DELETE" \\
  -host $META_SERVER -port $META_PORT \\
  -user '$SAS_USERNAME' -password "$SAS_PASSWORD" \\
  -deleteContents 2>&1
```

3. Execute the script (first making sure the batch tool exists) and fetch the log 

There should be no trace of the de-coded `SAS_PASSWORD` on either the local or remote system.

**Comment by allanbowe** [comment]
Following a recent poll, we plan to reduce our focus on SAS 9 EBI support:  https://www.linkedin.com/posts/allanbowe_sas-sasusers-activity-6940952346545840129-rO_y?utm_source=linkedin_share&utm_medium=member_desktop_web
