### ISSUE TITLE
Deploying issue in fresh sasjs app

### ISSUE THREAD

**Issue by YuryShkoda** [sasjs/cli#1176]
Steps to reproduce:
```shell
sasjs create new-issue
cd new-issue
sasjs cbd -t viya
```
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/25773492/159855585-05317a79-6cee-4338-9118-57728dd38a6a.png">

**Comment by allanbowe** [comment]
Closed by https://github.com/sasjs/cli/pull/1314

**Comment by sabhas** [comment]
via Hubstaff
User: Sabir Hassan

Project: SASjs cli - https://app.hubstaff.com/projects/2310875
Date Range: 02/01/23 - 02/02/23
Work session total: 5:51:01
Billable: Yes

Grand total: 5:51:01

**Comment by sabhas** [comment]
via Hubstaff
User: Sabir Hassan

Project: SASjs cli - https://app.hubstaff.com/projects/2310875
Date Range: 02/02/23 - 02/02/23
Work session total: 0:06:53
Billable: Yes

Grand total: 5:57:54
