### ISSUE TITLE
Run SAS Code from sasjs

### ISSUE THREAD

**Issue by shivakrishnay** [sasjs/cli#1184]
run a sas code which is available in git hub from sasjs

**Comment by allanbowe** [comment]
Hi @shivakrishnay  - can you please elaborate on the exact issue you are facing?  What is it you have tried, and what are you trying to do?

**Comment by allanbowe** [comment]
We support two approaches from running SAS code from GIT.  

1) As part of a regular SASjs project (compile/build/deploy from a GIT branch) as described here: https://communities.sas.com/t5/SAS-Global-Forum-Proceedings/Scaffolding-SAS-Projects-With-NPM-and-SASjs/ta-p/726347

2) Executing directly from an unsecured GIT repository using the `sasjs run` command as described here: https://cli.sasjs.io/run/#using-github-urls

**Comment by shivakrishnay** [comment]
Getting below error while ran the below code,

sasjs run github link -t sas9

 ERROR  An error has occurred when running your SAS code.                                                                                                                                                
 Error while handling error. unable to verify the first certificate

**Comment by allanbowe** [comment]
Hi @shivakrishnay - it sounds like your github repo is using self-signed certificates.  If your admin cannot configure the correct certificates, you can try the steps listed here:  https://github.com/sasjs/cli/issues/1181#issuecomment-1090638584

Alternatively, you can add the following entry to your target your `sasjs/sasjsconfig.json` file (or `~/.sasjsrc` if global):

```json
      "httpsAgentOptions": {
        "allowInsecureRequests": true
      },
```

**Comment by allanbowe** [comment]
We are assuming that this issue is resolved - if not feel free to raise another.
