### ISSUE TITLE
`sasjs request` on sasjs/server does not report a 401 response

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#1197]
When running `sasjs request` on [sasjs/server](https://github.com/sasjs/server) with an invalid access token, nothing is shown in the console despite the network request returning a 401 error code.

We should show a helpful message to the user, such as:  "401 received - please check credentials and re-run sasjs auth"

**Comment by allanbowe** [comment]
Current message shown is as below, which is acceptable:

![image](https://user-images.githubusercontent.com/4420615/214280115-f1d8774b-0570-48ae-8eed-176a55415414.png)

**Comment by sabhas** [comment]
via Hubstaff
User: Sabir Hassan

Project: SASjs cli - https://app.hubstaff.com/projects/2310875
Date Range: 01/24/23 - 01/24/23
Work session total: 1:51:58
Billable: Yes

Grand total: 1:51:58

**Comment by sabhas** [comment]
via Hubstaff
User: Sabir Hassan

Project: SASjs cli - https://app.hubstaff.com/projects/2310875
Date Range: 01/24/23 - 01/24/23
Work session total: 0:16:37
Billable: Yes

Grand total: 2:08:35
