### ISSUE TITLE
setting serverName in sasjsconfig

### ISSUE THREAD

**Issue by rudvfaden** [sasjs/cli#1218]
Hi. I tried to change serverName i `sasjsconfig.json`. 

```sh
    {
      "name": "sas9",
      "serverUrl": "https://sasweb-t.jbmain00.corp.jyskebank.net:8343",
      "serverType": "SAS9",
      "appLoc": "/BI/Datawarehouse/angular-seed-app",
      "deployConfig": {
        "deployServicePack": false
      },
      "serverName": "SASBIAppUTF8",
      "repositoryName": "Foundation"
    },
```

But when i build I still get `SASApp` in `sas9.sas`

```
%macro mm_createwebservice(path=
    ,name=initService
    ,precode=
    ,code=ft15f001
    ,desc=This stp was created automagically by the mm_createwebservice macro
    ,mDebug=0
    ,server=SASApp
    ,replace=YES
    ,adapter=sasjs
)/*/STORE SOURCE*/;
```

**Comment by allanbowe** [comment]
Indeed, this is a bug - we are not currently using that attribute when generating the SAS program.  We'll look into it asap

**Comment by allanbowe** [comment]
What needs to happen (**only** when `serverType` is `SAS9`):

- [ ] The generated build.sas needs a `%let serverName=$(serverName);` line at the top, underneath `compiled_apploc`
- [ ] The value should come from the `serverName` property of the target
- [ ] The default value, if none provided, should be `%let serverName=SASApp;`
- [ ] The `%mm_createwebservice()` macro in build.ts should be:  

```
      return `%mm_createwebservice(path=&appLoc/&path, name=&service, code=sascode, replace=yes, server=&serverName)`
```

**Comment by allanbowe** [comment]
@all-contributors please add @rudvfaden for bug reporting

**Comment by allanbowe** [comment]
@rudvfaden  - this issue is now fixed, please run `npm i -g @sasjs/cli` then `sasjs cb -t yoursas9target`

**Comment by rudvfaden** [comment]
It works. Thanks for fixing it so quick
