### ISSUE TITLE
Build issue caused by specific code

### ISSUE THREAD

**Issue by mblauw-sas** [sasjs/cli#1227]
The following two lines of code were present in my job:

```
/*Name_corrected2=translate(trim(Name_corrected),'_','`~!@#$%^&*()+-=[]\{}|;:",./<>?Â°²³µ ');
/* Name_corrected2=translate(trim(Name_corrected),'_','/','(',')','?','Â²','#','°C','µ','³'); */
```

Compilation of that job worked correctly. While building, however, these two lines caused about 50 lines to be excluded from the built code.

**Comment by allanbowe** [comment]
I was able to reproduce with these steps:

```bash
sasjs create mathieu -t jobs
cd mathieu
code .
```

I then pasted the two lines above into `jobs/load/runjob1.sas`.  After running `sasjs c` I can see that everything is fine:

<img width="765" alt="image" src="https://user-images.githubusercontent.com/4420615/179493034-0b0d7e1b-4d8e-4d63-a584-185795c77b84.png">

But after running `sasjs b` the rest of the file is truncated:

<img width="973" alt="image" src="https://user-images.githubusercontent.com/4420615/179493201-50d995b0-b298-479f-9d86-642fb801b29d.png">
