### ISSUE TITLE
Bug: services/files from react-seed-app copied incorrectly during compile/build/deploy

### ISSUE THREAD

**Issue by TeMeta** [sasjs/cli#1242]
added a simple Python test program `aaaaa.py` to `sasjs/services/files` and ran `sasjs cbd`.

Instead of copying the python program it decided to put the content of `upload.sas` into both files inside `sasjsbuild` instead
![image](https://user-images.githubusercontent.com/21976550/187047481-24410784-392c-46a1-a34c-fa29cce75fa4.png)

**Comment by allanbowe** [comment]
Yes - that is a bug!  However we don't support compilation yet for python / JS programs.

Instead, any python / JS content should be added in the `syncFolder` property.

Just add this to your `sasjs/sasjsconfig.json`:

```
{
  "$schema": "https://cli.sasjs.io/sasjsconfig-schema.json",
  "syncFolder": "sasjs/mystaticfolder",
  "targets": [

```

Then, any content under `sasjs/mystaticfolder` will be uploaded without modification.

**Comment by TeMeta** [comment]
Thanks @YuryShkoda, closing ticket. I realised that compiled version of services appended them in order for dependencies. The Python content was appended to the end of that file. Thanks for the clarification!
