### ISSUE TITLE
issue with deploying to SAS Viya 4

### ISSUE THREAD

**Issue by jangitje** [sasjs/cli#1270]
When compiling, building and deploying to SAS  Viya 4 (2022.09) the sas programs are not deployed with .sas extension.
In SAS Viya the job is recognized as a SAS definition, not a SAS job. Manually adding the .sas extension in SAS Viya does not work. When trying to run the job in SAS Viya, the job just hangs.

**Comment by jangitje** [comment]
Sorted it out already. This apparently works as designed. And the jobs actually run, it just takes some time.
I would like the option though to have it deployed as .sas jobs.

**Comment by allanbowe** [comment]
Hi @jangitje - that's correct, on Viya, Jobs / Services / Tests are all deployed as Viya Job Definitions (so, no .sas extension and not suitable for running in Studio).

You are not the first to request the ability to deploy as programs.  There is a workaround described in this issue:  https://github.com/sasjs/cli/issues/991

We would like to build this (as a new feature) however right now our team does not have access to a Viya environment.  If your customer / client is prepared to involve us somehow, or you have a SAS Viya environment you can make available, we'd be happy to make a start on it.
