### ISSUE TITLE
After: npm i @sasjs/cli and npm i @sasjs/cli@latest I'm receiving ERROR when calling sasjs on cmd

### ISSUE THREAD

**Issue by bendanielsbacka** [sasjs/cli#1348]
Error states:
36 verbose stack Error: could not determine executable to run
36 verbose stack     at getBinFromManifest (C:\Users\...\AppData\Roaming\npm\node_modules\npm\node_modules\libnpmexec\lib\get-bin-from-manifest.js:17:23)
36 verbose stack     at exec (C:\Users\...\AppData\Roaming\npm\node_modules\npm\node_modules\libnpmexec\lib\index.js:188:15)
36 verbose stack     at async module.exports (C:\Users\...\AppData\Roaming\npm\node_modules\npm\lib\cli.js:89:5)

Also for example: "npx sasjs create project_name" produces error: "npm ERR! could not determine executable to run"

**Comment by bendanielsbacka** [comment]
> Error states: 36 verbose stack Error: could not determine executable to run 36 verbose stack at getBinFromManifest (C:\Users...\AppData\Roaming\npm\node_modules\npm\node_modules\libnpmexec\lib\get-bin-from-manifest.js:17:23) 36 verbose stack at exec (C:\Users...\AppData\Roaming\npm\node_modules\npm\node_modules\libnpmexec\lib\index.js:188:15) 36 verbose stack at async module.exports (C:\Users...\AppData\Roaming\npm\node_modules\npm\lib\cli.js:89:5)

Also for example: "npx sasjs create project_name" productes error: "npm ERR! could not determine executable to run"

**Comment by bendanielsbacka** [comment]
Hi,

Thank you very much for your ultra quick response! I just explained my colleagues in our organization that sasjs is definitely the best choice for unit testing and later on for other innovations you have made to sasjs would help us a lot to streamline our macro development process.

There must be some weird local problem with specific to my computer settings since my colleague successfully tested cli (with same node.js, npm, CMS, win10) I heard it is also successfully installed in rhel7 sas Viya server . I used many hours to figure out what was my problems but couldn't solve it. Maybe I'll get it working next week. Otherwice I might actually need your help. I'm not currently working so I can't provide more specs you asked for.

Thank you again for quick response. Have a nice weekend and all the best with your great job you are doing!

- Ben Danielsbacka, Statistics Finland



________________________________

**Comment by allanbowe** [comment]
Thanks Ben, you're very welcome, and glad to hear you are all making good use of SASjs!

I would suggest completely removing NodeJS / NPM and installing again from scratch.

If you would like help setting up `sasjs doc`, `sasjs test`, `sasjs flow` or even `sasjs cbd` feel free to join our public matrix room:  https://matrix.to/#/#sasjs:4gl.io

As you have confirmed the command is working in other Windows machines (with the same setup), and on RHEL7 SAS Viya, I will close the ticket.

Best,
Allan

**Comment by bendanielsbacka** [comment]
Thanks for matrix link. I actually have cleaned nodeJS/npm multiple times, but I will find the solution eventually 😊

Just a side note I'm a big fan of yours Allan and it's privilege to receive email straight from you! I have followed your work and used your stuff all the way from h45s but haven't tested many other products you have developed with your team recently. Currently I'm choosing/balancing between sas institute own vs code extension vs. sasjs extension. Maybe sasjs is better to use with sasjs server.


Sorry for long message, I'm just quite excited 😂 All the best with your new company!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by allanbowe** [comment]
About the extension - it's not an either/or.  Since SAS produced an official extension, we've switched focus to the areas they don't (and perhaps won't) support - such as Base SAS support (with SASjs Server), doc generation, linting, auto-compile & deploy of Jobs/Services/Tests, and support for non-proprietary instances of VS Code such as Codium and Theia.

You can use both, side by side.  

Thanks for the support!  I don't have your contact details - feel free to mail privately on allan@4gl.io and I'd be happy to help out with any SASjs questions or queries.
