### ISSUE TITLE
Create launcher context for every compute context

### ISSUE THREAD

**Issue by YuryShkoda** [sasjs/cli#182]
On `sasjs context create` command new launcher context should be created first and used to create a new compute context.

**Comment by allanbowe** [comment]
probably the best approach for this is to create a `sasjs launchercontext` command, this provides flexibility to mix and match launchers

**Comment by YuryShkoda** [comment]
Agreed on:
- if the command is `sasjs context create ...`, launcher context should be created automatically first and been used as a launcher context for the upcoming context.
- if `--launcherOnly` flag was provided, only the launcher context should be created.

**Comment by YuryShkoda** [comment]
UPD:
- if no launcherContext, we will create compute without launcher
- if contextName exists, use it as a launcher
- if contextName does not exist we can create a new launcher and use it as a launcher for the new compute context
