### ISSUE TITLE
sasjs job execute issue

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#221]
for some reason the `sasjs job execute` command is adding a _local_ filepath to the provided path.

SAS jobs _always_ execute on the server, so wouldn't expect this.

Also, the message says it has been submitted but that can't be correct as in fact it wasn't found:

![image](https://user-images.githubusercontent.com/4420615/98731667-57d03580-239e-11eb-850d-a230245225eb.png)

**Comment by saadjutt01** [comment]
Putting two forward slashes is the solution

POSIX path conversion: http://www.mingw.org/wiki/Posix_path_conversion

**Comment by YuryShkoda** [comment]
@saadjutt01 we should handle such case
