### ISSUE TITLE
sasjs flow

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#249]
The official SAS Job Flow creator is a licensed product and not all clients will have it available.  So we need to create a rudimentary scheduler.  This will take a JSON file as input, and submit all the jobs sequentially, logging the results to an output CSV.

If a job errors, then the flow stops.

The input JSON will look like this:

```
{
  "name": "myAmazingFlow",
  "flows": {
    "firstflow": {
      "jobs": [
        {
          "location": "/Projects/job1"
        },
        {
          "location": "/Projects/job2"
        },
        {
          "location": "/Projects/job3"
        }
      ],
      "predecessors": []
    },
    "secondflow": {
      "jobs": [
        {
          "location": "/Projects/job11"
        }
      ],
      "predecessors": [
        "firstflow"
      ]
    },
    "anotherflow": {
      "jobs": [
        {
          "location": "/Public/job15"
        }
      ],
      "predecessors": [
        "firstflow",
        "secondflow"
      ]
    }
  },
    "yetanotherflow": {
      "jobs": [
        {
          "location": "/Public/job115"
        }
      ],
      "predecessors": []
    }
  }
}
```

This will contain a flow with 4 milestones:   

1. firstflow  (triggers 3 jobs at once, runs immediately as no predecessors
2. yetanotherflow (triggers 1 job, runs immediately as no predecesors)
3. secondflow (triggers as soon as firstflow is complete and ONLY if the jobs all finish with SUCCESS status)
4. anotherflow (triggers once firstflow and secondflow are complete, but ONLY if all finish with SUCCESS)

As soon as each job is complete, a CSV file is updated showing hte following attributes:

* jobLocation
* startTime
* endTime
* duration (formatted)
* logLocation

Syntax:

```
sasjs flow execute --source /local/flow.json --logFolder /local/log/folder --csvLocation /local/some.csv
```

**Comment by YuryShkoda** [comment]
I would change the syntax to `sasjs flow execute --source /local/flow.json --log /local/log/folder -- /local/some.csv` to go inline with other commands

**Comment by YuryShkoda** [comment]
Agreed syntax: `sasjs flow execute --source /local/flow.json --logFolder /local/log/folder --csvFile /local/some.cs`
