### ISSUE TITLE
log in sasjs job execute is truncated

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#273]
Whenever fetching the log from the API we need to set the `?limit=100000` parameter to avoid truncation

**Comment by allanbowe** [comment]
conversation with @saadjutt01  - this is actually a fix to be made in the Adapter

**Comment by saadjutt01** [comment]
```
"logStatistics": {
    "lineCount": 757,
    "modifiedTimeStamp": "2020-12-01T09:31:50Z"
  },
```

Using `lineCount` in `log` Endpoint as `limit`
