### ISSUE TITLE
add return code to `sasjs job execute`

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#284]
To facilitate integration with job schedulers such as jenkins it would help if the `sasjs job execute` command would provide a return code indicating the success (or failure) of a job.

such return codes would be (taking sasbatch.sh as example):

* `0` - success
* `1` - warning
* `2` - error

There is however one "catch" in that it is a common use case to ignore warning conditions (eg when the licence is expiring).  For this reason we should enable a new flag ( `--ignoreWarnings`) on `sasjs job execute` which will return a `0` when the job state is `warning`.

The above return codes only apply when `--wait` is in effect.  if the job returns immediately, then nothing should be returned.

**Comment by YuryShkoda** [comment]
add flags:
1. `returnStatusOnly` - command will return status code only (status codes: 0,1,2)
2. `ignoreWarnings` - if enabled, then status 1 should be equal to 0
