### ISSUE TITLE
sasjs job execute is not waiting for the output

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#317]
Problem:

Log is being truncated

Cause:

We are fetching the lineCount from logStatistics before the job has completed

![image](https://user-images.githubusercontent.com/4420615/101469848-87467380-3945-11eb-9e4b-19bbb6060e9b.png)

Final linecount:

![image](https://user-images.githubusercontent.com/4420615/101469883-94636280-3945-11eb-887f-4ec80d82091c.png)

**Comment by YuryShkoda** [comment]
`--output` should point to the file instead of a folder
