### ISSUE TITLE
sasjs not available on npx

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#326]
![image](https://user-images.githubusercontent.com/4420615/101630740-9a2f7580-3a23-11eb-938f-9e7dd0e63009.png)

![image](https://user-images.githubusercontent.com/4420615/101631635-f050e880-3a24-11eb-97d2-e27b16408729.png)

Expected - should be able to run `npx sasjs -v`

**Comment by saadjutt01** [comment]
> Unless a --package option is specified, **npx will try to guess the name of the binary** to invoke depending on the specifier provided. All package specifiers understood by npm may be used with npx, including git specifiers, remote tarballs, local directories, or scoped packages.

Reference: https://github.com/npm/npx

Currently, `npx -p @sasjs/cli sasjs --help` works.

**Comment by allanbowe** [comment]
The workaround for this is to use the fully qualified reference, eg `npx @sasjs/cli <command>`
