### ISSUE TITLE
Add handlers for SIGINT and SIGTERM

### ISSUE THREAD

**Issue by allanprc** [sasjs/cli#350]
Currently if a `sasjs job execute` process is terminated, the SAS job continues to execute on the server.  

We should handle termination gracefully by cancelling the running job and fetching the log.

OS Signal events may be handled in a fashion such as described [here](https://github.com/informa-ibi/lliprc_datamanagement/pull/31) and [here](https://github.com/informa-ibi/lliprc_datamanagement/pull/31).

The SAS process can be cancelled by setting the session state as described here:  https://developer.sas.com/apis/rest/v3.5/Compute/#set-state-of-a-session

The process should be as follows:

1.  Receive kill / termination signal
2. Display console message (type of signal received, please wait whilst tidy up takes place)
2.  Send the cancel message (set session state)
3.  Display console message (Cancel message sent, show the URI)
4.  Fetch the log
5.  Display a 'termination complete' message with a link to the log.
6.  terminate

The above should be applicable to the following commands:

* `sasjs job execute`
* `sasjs run`
* `sasjs request`
* `sasjs flow execute`

**Comment by allanbowe** [comment]
We can implement this HOWEVER, it should be noted that setting the job state to "canceled" doesn't stop the job from running on the server; the job will run to completion.

**Comment by allanbowe** [comment]
On the basis that this doesn't actually stop the job from running (so, therefore pointless) am closing the ticket - will re-open if the situation changes
