### ISSUE TITLE
large logs need to be fetched and parsed in chunks

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#435]
When we receive large log files (eg 50mb and above) this breaks the json.parse() function

![image](https://user-images.githubusercontent.com/4420615/106340406-fd0df200-6299-11eb-97df-545645bf80ac.png)

Rather than attempt to fetch the whole log, we should retrieve it and write it out in chunks.

- [ ] create a test that makes a large log, which replicates the issue
- [ ] fix the issue

Example SAS code for a large log:

```
data _null_;
  y=repeat('W',500);
  do x=1 to 1e6;
    putlog y=;
  end;
run;
```

**Comment by YuryShkoda** [comment]
The adapter should keep fetching log in chunks (up to 10000 lines each) until the whole log has been retrieved.
`start` parameter should be provided to the GET request to indicate the chunk start line.
