### ISSUE TITLE
sasjs add cred not recognising targets in the sasjconfig.json

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#447]
This is happening in the Data Controller repo - simply clone the repo, checkout the development branch, and run `sasjs add cred -t viya`

For some reason it's not picking up the viya target

![image](https://user-images.githubusercontent.com/4420615/107085522-e830e180-67f8-11eb-8241-40837ad23a5a.png)

**Comment by krishna-acondy** [comment]
@allanbowe I was unable to replicate this. It seems to just work when I try it.
![image](https://user-images.githubusercontent.com/2980428/107119679-1bb74e80-6881-11eb-803d-fd1ae936dfd7.png)
