### ISSUE TITLE
sasjs compile for a single file

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#469]
For a large project it can be time consuming to compile and deploy every service.  In addition, for our upcoming VSCode plugin, we need a way to compile and run a single Job or Service.

Proposal - we add two new actions to the `sasjs compile` command, eg:

`sasjs compile job -s myjob.sas -t mytarget -o /some/folder`

and

`sasjs compile service -s myservice.sas -t mytarget`

So will then have three 'compile' commands:

* `sasjs  compile` -> compiles everything in a SASjs project, works locally
* `sasjs compile  job` -> compiles  a single job, can work anywhere
* `sasjs compile service` -> compiles a single service, can work anywhere

Arguments:

--source (alias -s) - the path/name.ext of the individual source file to compile (as job or service).  MANDATORY
--target (alias -t) - The target to use for obtaining the source folders of programs and macros.  If it is not specified, the first target is used by default.  The target can exist either in the local project configuration or in the global .sasjsrc file.  OPTIONAL
--output (alias -o) - path where output of the compiled job or service will be saved.  OPTIONAL.  If not provided, the output will go to the root of the sasjsbuild folder if in a project (sasjsbuild would be emptied first), else in the current working directory.  

The created job or service will have the same name as the source file.

**Comment by saadjutt01** [comment]
the output would be saved as per the --output location,

if in a project, then it would go in the root of the sasjsbuild folder
if global, create sasjsbuild and place there
