### ISSUE TITLE
Create package.json when running sasjs init if it doesn't already exist

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#527]
When running `sasjs init` in a clean directory, the subsequent `sasjs compile` will fail due to the missing @sasjs/core dependency.

For this reason we must create a `package.json` file if it does not exist, and run `npm i` so that the user can immediately start compiling SAS code.

**Comment by saadjutt01** [comment]
Can you confirm what's described in this ticket?

Because, its seems working fine, in clean directory.

![image](https://user-images.githubusercontent.com/8914650/109861784-7de95080-7c81-11eb-801f-e7199c336e04.png)

**Comment by allanbowe** [comment]
closing as could not reproduce
