### ISSUE TITLE
Adding target name with sasjs add can cause strange cursor behaviour

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#529]
I wasn't able to reproduce this consistently but Krishna did find the cause of it, which is the underlying prompts library.

There is a pull request for it here:  https://github.com/terkelg/prompts/pull/297

And the Issue is described here: https://github.com/terkelg/prompts/issues/249

Once the library is updated, we should rebuild & redeploy with their latest version.

**Comment by krishna-acondy** [comment]
@allanbowe I've just raised a PR for that issue. Hopefully that'll get merged in soon. 🤞🏽

https://github.com/terkelg/prompts/pull/300

**Comment by krishna-acondy** [comment]
Fixed.
