### ISSUE TITLE
sasjs run command - to sasjsresults folder

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#569]
Currently when running `sasjs run` we stick the log in the current directory by default.  This can create a lot of unwanted files within a local project repository.

Instead, if running with a local target, we should write the log to a `sasjsresults/log` folder (alongside the sasjsbuild folder).  the `sasjsresults` folder should be configurable, like sasjsbuild.  If running for a global target, the current behaviour (write to current directory) is ok.

- [ ] sasjsresults folder is configurable
- [ ] logs for sasjs run, when running for a local target, are written to the sasjsresults/logs folder

**Comment by saadjutt01** [comment]
if outside project, `sasjsresults` will be relative to `home` directory, as we do for `sasjsbuild` from global Config.
