### ISSUE TITLE
sasjs doc fails when @brief attribute contains double quotes

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#578]
To reproduce, open this link:  https://gitpod.io/#github.com/sasjs/template_jobs

Then update the job header as per this screenshot and run `sasjs doc`

![image](https://user-images.githubusercontent.com/4420615/112212669-8e0ba480-8c1d-11eb-823f-81926965315e.png)

embedded quotes need to be escaped in the DOT file before they can be rendered.

It would also be nice if the DOT file would be saved in the sasjs doc output folder before it is rendered.  This would help with debugging, as well as diagram re-use.

- [ ] sasjs doc supports quotes in the BRIEF when data lineage is enabled
- [ ] DOT output is saved in doc output folder
- [ ] at least one new test case is created

**Comment by saadjutt01** [comment]
> It would also be nice if the DOT file would be saved in the sasjs doc output folder before it is rendered. This would help with debugging, as well as diagram re-use.

this part is already working, before this crash, cli saves DOT file in _sasjsbuild/docs_ directory
_Syntax error of line 11_ is of Dot file.
