### ISSUE TITLE
install warnings

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#6]
We need to address the following warnings when installing sasjs cli

```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
```

**Comment by krishna-acondy** [comment]
@allanbowe @YuryShkoda The warnings are because of our dependency on `JSDOM`. We use that package to parse HTML files and replace asset paths etc.
The warnings will automatically go away when this issue is resolved: https://github.com/jsdom/jsdom/issues/2792

**Comment by YuryShkoda** [comment]
As an option, we can update our readme with the silent npm install command 'npm i -g -s @sasjs/cli' (or --silent)

**Comment by gustawdaniel** [comment]
for this issue, there is created pull request 

https://github.com/jsdom/jsdom/pull/3031

**Comment by krishna-acondy** [comment]
@gustawdaniel Many thanks! 🙌 We'll watch that PR and bump our `jsdom` version when a new one is available.

**Comment by allanbowe** [comment]
We are now waiting for this PR:  https://github.com/jsdom/jsdom/pull/3092

**Comment by krishna-acondy** [comment]
@allanbowe @saadjutt01 It might be better to find an alternative to JSDOM. One of us should take some time to investigate.

**Comment by allanbowe** [comment]
It's merged now!
