### ISSUE TITLE
User Friendly message when refresh token expires

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#612]
We had a couple of support calls recently due to 401 authorisation issues when running `sasjs deploy` or `sasjs run`

The reason was due to the REFRESH_TOKEN expiring

Rather than attempt a connection with an expired token, we should decode the JWT and present a friendly message to the user, eg:

```
The Refresh token for Client $(CLIENT_ID) expired on $(REFRESH_EXPIRY_DTTM).
Please re-authenticate by running sasjs add cred -t $(TARGET_NAME)

Tip - askyour SAS Administrator to generate a client/secret pair with a longer expiry period
```

**Comment by krishna-acondy** [comment]
The adapter throws a `LoginRequiredError` when there is a 401. Maybe we can use this to display the error message above?
