### ISSUE TITLE
sasjs run completes executing before job is finished

### ISSUE THREAD

**Issue by mblauw-sas** [sasjs/cli#613]
When running a specific job using the sasjs run command, it completes and fetches the log before the job is completed in Viya. 

![image](https://user-images.githubusercontent.com/76040062/115416749-554cf400-a1f8-11eb-82dc-23ac36762f80.png)

![image](https://user-images.githubusercontent.com/76040062/115416515-23d42880-a1f8-11eb-8a6a-17a53cb5e271.png)

**Comment by allanbowe** [comment]
- [ ] Update the `sasjs run` documentation (and JSDOC docs) to confirm the exact response codes / logic used to indicate the end of a job run

**Comment by krishna-acondy** [comment]
@allanbowe Would this have been fixed by this other bugfix we did in the adapter? https://github.com/sasjs/adapter/pull/359

**Comment by allanbowe** [comment]
I contacted @mblauw-sas and the issue has not occurred since that fix was deployed.  So will close it, pending any further updates.
