### ISSUE TITLE
ghooks not found

### ISSUE THREAD

**Issue by tmoody** [sasjs/cli#684]
When submitting git commands in my SASjs project I am getting this message in the log:

```
ghooks not found!
Make sure you have it installed on your "node_modules".
Skipping git hooks.
```
However, I do have the `build/node_modules/ghooks` folder in the project.

**Comment by allanbowe** [comment]
This is due to some implicit behaviour by the ghooks devDependency in the sasjs/core library.  I'll pick this one up
