### ISSUE TITLE
remove .git folder after instantiation

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#71]
currently when installing react, angular or minimal templates we leave behind a .git folder.  This is a problem for two reasons:

1 - we don't actually want users to push to that repo
2 - it causes problems when running the command within existing repos

Definition of done - the .git folder is removed following the git clone for template installs

**Comment by krishna-acondy** [comment]
This has been implemented here: https://github.com/sasjs/cli/blob/main/src/utils/utils.js#L45
