### ISSUE TITLE
ability to manage contexts from the CLI

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#74]
We need the following commands, which are based on their equivalents in the [adapter](https://github.com/sasjs/adapter)

```
sasjs context create

sasjs context edit

sasjs context delete
```

We could change the names of the commands if it makes sense.  OR we figure out a generic way to run the `sasjs` functions.

The edit part depends on #https://github.com/sasjs/adapter/issues/73

**Comment by YuryShkoda** [comment]
done
