### ISSUE TITLE
problems with sasjs run command

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#75]
As demonstrated here:  

[![asciicast](https://asciinema.org/a/sBCuamFPKdB0KPMHvsvQhszX3.svg)](https://asciinema.org/a/sBCuamFPKdB0KPMHvsvQhszX3)

Steps:

```
sasjs create demo -t sasonly
cd demo
sasjs add  #follow the steps
sasjs run package.json -t [target]
```

I expected it to error (the `package.json` is not a valid sas file) however the SAS log should have been returned (or an error handler should have provided more explicit details of what went wrong)

**Comment by allanbowe** [comment]
Issue 2 may be due to a problem with `sasjs add` rather than `sasjs run` - and may instead be covered by this ticket: #https://github.com/sasjs/cli/issues/76

**Comment by medjedovicm** [comment]
The reason for this issue is the issue with @sasjs/adapter, where access token is not passed to session manager.

**Comment by krishna-acondy** [comment]
@allanbowe / @medjedovicm Is this now fixed?

**Comment by YuryShkoda** [comment]
> @allanbowe / @medjedovicm Is this now fixed?
no

**Comment by YuryShkoda** [comment]
![image](https://user-images.githubusercontent.com/25773492/94902872-8b679800-04a1-11eb-9678-c6200df526c8.png)
