### ISSUE TITLE
sasjs doc - UNC and lineage issues

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#757]
There are two issues with sasjs doc:

1) UNC paths not supported.  

This is actually a doxygen limitation on windows, however to avoid confusion, we should identify such paths (eg by the fact they start with `\\`) and notify the user as follows:

> UNC paths are not supported.  Please map to a network drive, or migrate the project to an existing path (with a drive letter).

2) Lineage 

Currently the lineage is not being picked up when the doxygen header is as follows:

```sas
/* 
  just one asterisk
*/
```

This approach works fine for sasjs compile, so it should work also for sasjs doc / lineage generation.

**Comment by saadjutt01** [comment]
Since,  it's doxygen's limitation to use comment block with double asterisks ( requires to start with double asterisks )
Reference: https://www.doxygen.nl/manual/docblocks.html#cppblock

Need to update `lint` for rule: `hasDoxygenHeader`
