### ISSUE TITLE
authInfo should be removed from `sasjsconfig.json`

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#76]
For security, the authinfo properties should not be inserted into the sasjsconfig.json file.  

When running sasjs add in LOCAL the .env file should contain the following:
*  `access_token` 
*  `refresh_token`
* `client_id`
* `client_secret`

When running in global, they can go in the .sasjsrc file.

In terms of the CLIENT and SECRET, these could also go in the target (two new properties, `client_id` and `client_secret`).  The values in the `.env` file would take precedence over those in the target.

# .env

The project would have a main .env file as a fallback for all local targets.  The primary file will be `.env.[targetname]`.

# credentialsFile
The sasjsconfig.json file will also have an optional property (`"credentialsFile":"../../path/to/creds.file",`) that overrides all implicit settings and states explicitly where the credentials are sourced from.

**Comment by krishna-acondy** [comment]
@allanbowe If we're happy enough with the way we handle credentials now, can we close this?
