### ISSUE TITLE
npm WARN deprecated querystring@0.2.0

### ISSUE THREAD

**Issue by allanbowe** [sasjs/cli#847]
We are getting the following warning when installing the CLI:
```
npm WARN deprecated querystring@0.2.0:
```

![image](https://user-images.githubusercontent.com/4420615/125408836-fd232980-e3c3-11eb-9c34-989fce8a24f5.png)

Expected behaviour - the CLI should install with zero warnings or errors

**Comment by jimmywarting** [comment]
guess you are suppose to report it to https://github.com/sasjs/adapter that have a dependency on url that looks like it is not being used?

**Comment by allanbowe** [comment]
Quite right @jimmywarting, thanks for the spot!  We have an adapter PR underway, @saadjutt01 is investigating.

https://github.com/sasjs/adapter/pull/467

**Comment by allanbowe** [comment]
For reference, here is the PR that deprecated querystring: https://github.com/Gozala/querystring/pull/52

As per the homepage:

> The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
