### ISSUE TITLE
cert issue for sas9 when submit jobs

### ISSUE THREAD

**Issue by venkattoluchuri** [sasjs/cli#862]
bash-3.2$ sasjs run https://raw.githubusercontent.com/venkattoluchuri/sas/main/test.sas -t sas9
ℹ Target sas9 was found in your local sasjsconfig.json file.                                                14:02:53

 ERROR  An error has occurred when running your SAS code.                                                   14:02:54
 Error while handling error. unable to verify the first certificate

bash-3.2$

**Comment by allanbowe** [comment]
Potential cause for the issue - second parameter here should be taken from the config:  https://github.com/sasjs/adapter/blob/master/src/job-execution/Sas9JobExecutor.ts#L22
