### ISSUE TITLE
Only run a small set of tests against the server

### ISSUE THREAD

**Issue by krishna-acondy** [sasjs/cli#881]
We are currently running over 100 tests against the SAS server on each push/PR. We need to whittle this down so we can reduce the load on the server and speed up the feedback loop for developers.
We can do this by isolating a small set of tests to be run against the server, and using mocks to simulate server responses on all other tests.

**Comment by allanbowe** [comment]
Closing in favour of #1202 (we will only run tests for a single server type).  We have also done quite a bit of work on mocking since this ticket was raised.
