### ISSUE TITLE
No PID get create when we run sasjs run with Git stored code

### ISSUE THREAD

**Issue by venkattoluchuri** [sasjs/cli#906]
bash-3.2$ sasjs run https://github.xxxx.com/raw/xxx/codes/master/test.sas
ℹ No target was specified. Falling back to default target 'viya' from your local sasjsconfig.json file.                      18:37:36
ℹ Sending temp-1627996055039.sas to SAS server for execution.                                                                18:37:36
ℹ Polling session status...                                                                                                  18:37:42
ℹ Current session state is 'idle'                                                                                            18:37:44
ℹ Polling session status...                                                                                                  18:37:47
ℹ Job has been submitted for 'exec-temp-1627996055039.sas'.                                                                  18:37:50
ℹ You can monitor the job progress at 'https://xxxxxxxxxx/compute/sessions/7a47c00b-5e5c-4ac4-9b29-30c667839d55-ses0000/jobs/A36B4CF3-B874-AE4A-B2EE-C23CB7CEE8DB/state'.
ℹ Fetching logs from line no: 1 to 159 of 159.                                                                               18:37:53
✔ Job execution completed!                                                                                                   18:37:55
ℹ Creating log file in /Users/vt7/Desktop/demo/sasjsresults .                                                                18:37:55
✔ Log file has been created at /Users/vt7/Desktop/demo/sasjsresults/sasjs-run-20210803130755.log .

**Comment by allanbowe** [comment]
To clarify - we can add the PID but we can only do that for executions on Viya (won't be supported on SAS 9)

**Comment by allanbowe** [comment]
In viya 4 the pid won't be so interesting - closing this one due it having limited benefit (unless a sponsor can be found)
